version: '3.9'
services:
  trooper-ms-product:
    container_name: ms-product
    build: ./
    ports:
      - 3001:3001
    volumes:
      - ./:/app/ms-product
    environment:
      - JWT_SECRET=MTk4OGExOTZkMWYyOWZjZjlmOTcwMWVjZWRjMzc1MzZkOGM0MmFjMjQ0NjcyZjIzZDQwOGU4YTQ1YWQ3NTRjZA==
    depends_on:
      - mongodb-ms-product

  mongodb-ms-product:
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - mongodb-product-volume-docker:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret

  mongodb-ms-product-test:
    image: mongo:5
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret

volumes:
  mongodb-product-volume-docker:

networks: 
  default:
    name: trooper-network
    external: true
