version: '3.9'
services:
  trooper-ms-product:
    container_name: ms-product
    build: ./
    ports:
      - 3001:3001
    volumes:
      - ./:/app/ms-product
    environment:
      - PORT=3001
      - DB_HOST=mongodb-ms-product
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=ms-product
      - JWT_SECRET=MTk4OGExOTZkMWYyOWZjZjlmOTcwMWVjZWRjMzc1MzZkOGM0MmFjMjQ0NjcyZjIzZDQwOGU4YTQ1YWQ3NTRjZA==
    depends_on:
      - mongodb-ms-product

  mongodb-ms-product:
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - mongodb-product-volume-docker:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret

volumes:
  mongodb-product-volume-docker: